# Generated by Django 3.2 on 2021-08-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.jpg', null=True, upload_to=''),
        ),
    ]
